const frases = [
  "Tú puedes con todo.",
  "Nunca dejes de creer en ti.",
  "El éxito es el resultado del esfuerzo constante.",
  "Cada día es una oportunidad para ser mejor.",
  "La actitud lo es todo.",
  "Sigue tus sueños y no dejes que nadie te detenga.",
  "La perseverancia es la clave del éxito.",
  "Las oportunidades no ocurren. Las creas.",
  "La confianza en uno mismo es el primer secreto del éxito.",
  "El único límite es el que te pones a ti mismo.",
  "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
  "La vida es corta, haz que cada día cuente.",
  "Cada logro comienza con la decisión de intentarlo.",
  "El éxito es un camino, no un destino.",
  "La mejor manera de predecir el futuro es crearlo.",
  "Si te caes siete veces, levántate ocho.",
  "Aprovecha el día.",
  "Sé el cambio que quieres ver en el mundo.",
  "Cree en ti mismo y todo es posible.",
  "La magia está en ti.",
  "La vida es un regalo, nunca dejes de dar gracias.",
  "El fracaso es la oportunidad de comenzar de nuevo con más inteligencia.",
  "Hoy es el primer día del resto de tu vida.",
  "Nunca es tarde para ser lo que podrías haber sido.",
  "Sé valiente, incluso si tienes miedo.",
  "No mires atrás, no vas en esa dirección.",
  "Eres más fuerte de lo que crees.",
  "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.",
  "No importa lo lento que vayas mientras no te detengas.",
  "La vida es 10% lo que sucede y 90% cómo reaccionas ante ello.",
  "Los sueños no tienen fecha de caducidad.",
  "La clave es comenzar antes de estar listo.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "Si puedes soñarlo, puedes lograrlo.",
  "Todo es posible para el que cree.",
  "Sé el tipo de persona que quieres conocer.",
  "El optimismo es la fe que conduce al logro.",
  "Nada es imposible, la palabra misma dice 'I'm possible' (Soy posible).",
  "No importa cuántas veces fracases, debes seguir intentándolo.",
  "La única forma de hacer un gran trabajo es amar lo que haces.",
  "Cada día es una nueva oportunidad para cambiar tu vida.",
  "Sigue adelante incluso cuando te sientas inseguro.",
  "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Los retos son lo que hacen la vida interesante y superarlos es lo que la hace significativa.",
  "Las oportunidades no ocurren. Las creas.",
  "Si te caes siete veces, levántate ocho.",
  "La vida es un regalo, nunca dejes de dar gracias.",
  "El fracaso es la oportunidad de comenzar de nuevo con más inteligencia.",
  "Hoy es el primer día del resto de tu vida.",
  "Nunca es tarde para ser lo que podrías haber sido.",
  "Sé valiente, incluso si tienes miedo.",
  "No mires atrás, no vas en esa dirección.",
  "Eres más fuerte de lo que crees.",
  "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.",
  "No importa lo lento que vayas mientras no te detengas.",
  "La vida es 10% lo que sucede y 90% cómo reaccionas ante ello.",
  "Los sueños no tienen fecha de caducidad.",
  "La clave es comenzar antes de estar listo.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "Si puedes soñarlo, puedes lograrlo.",
  "Todo es posible para el que cree.",
  "Sé el tipo de persona que quieres conocer.",
  "El optimismo es la fe que conduce al logro.",
  "Nada es imposible, la palabra misma dice 'I'm possible' (Soy posible).",
  "No importa cuántas veces fracases, debes seguir intentándolo.",
  "La única forma de hacer un gran trabajo es amar lo que haces.",
  "Cada día es una nueva oportunidad para cambiar tu vida.",
  "Sigue adelante incluso cuando te sientas inseguro.",
  "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Los retos son lo que hacen la vida interesante y superarlos es lo que la hace significativa.",
  "Las oportunidades no ocurren. Las creas.",
  "Si te caes siete veces, levántate ocho.",
  "La vida es un regalo, nunca dejes de dar gracias.",
  "El fracaso es la oportunidad de comenzar de nuevo con más inteligencia.",
  "Hoy es el primer día del resto de tu vida.",
  "Nunca es tarde para ser lo que podrías haber sido.",
  "Sé valiente, incluso si tienes miedo.",
  "No mires atrás, no vas en esa dirección.",
  "Eres más fuerte de lo que crees.",
  "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.",
  "No importa lo lento que vayas mientras no te detengas.",
  "La vida es 10% lo que sucede y 90% cómo reaccionas ante ello.",
  "Los sueños no tienen fecha de caducidad.",
  "La clave es comenzar antes de estar listo.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "Si puedes soñarlo, puedes lograrlo.",
  "Todo es posible para el que cree.",
  "Sé el tipo de persona que quieres conocer.",
  "El optimismo es la fe que conduce al logro.",
  "Nada es imposible, la palabra misma dice 'I'm possible' (Soy posible).",
  "No importa cuántas veces fracases, debes seguir intentándolo.",
  "La única forma de hacer un gran trabajo es amar lo que haces.",
  "Cada día es una nueva oportunidad para cambiar tu vida.",
  "Sigue adelante incluso cuando te sientas inseguro.",
  "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Los retos son lo que hacen la vida interesante y superarlos es lo que la hace significativa.",
];

document.addEventListener("DOMContentLoaded", function () {
  const botonGenerarFrase = document.getElementById("generarFrase");
  const fraseElement = document.getElementById("frase");

  botonGenerarFrase.addEventListener("click", function () {
    const randomIndex = Math.floor(Math.random() * frases.length);
    fraseElement.textContent = frases[randomIndex];
  });
});
